# Generated by Django 5.0.6 on 2024-05-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
